In [1]:
import numpy as np

In [2]:
a =  np.random.randint(10, size = (5,5))
a

array([[1, 2, 3, 7, 9],
       [9, 7, 7, 3, 6],
       [3, 5, 8, 0, 5],
       [9, 8, 2, 2, 7],
       [7, 5, 3, 8, 6]])

In [3]:
alt_a = a[0:3, 0:2]
alt_a

array([[1, 2],
       [9, 7],
       [3, 5]])

In [4]:
alt_a[0,0] = 9999
alt_a[1,1] = 888

In [5]:
alt_a

array([[9999,    2],
       [   9,  888],
       [   3,    5]])

In [7]:
a
#alt kume degisikligi ana kumeyi de etkiledi

array([[9999,    2,    3,    7,    9],
       [   9,  888,    7,    3,    6],
       [   3,    5,    8,    0,    5],
       [   9,    8,    2,    2,    7],
       [   7,    5,    3,    8,    6]])

In [8]:
m =  np.random.randint(10, size = (5,5))
m

array([[4, 2, 2, 4, 8],
       [5, 0, 0, 9, 5],
       [5, 5, 8, 2, 1],
       [9, 9, 4, 2, 3],
       [7, 8, 7, 6, 6]])

In [10]:
alt_m = m[0:3, 0:2].copy()

In [12]:
alt_m[0,0] = 999

In [13]:
alt_m

array([[999,   2],
       [  5,   0],
       [  5,   5]])

In [14]:
m

array([[4, 2, 2, 4, 8],
       [5, 0, 0, 9, 5],
       [5, 5, 8, 2, 1],
       [9, 9, 4, 2, 3],
       [7, 8, 7, 6, 6]])