In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [4]:
y = np.array([4,5,6])

In [5]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [6]:
z = np.array([7,8,9])

In [7]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#iki boyut
a = np.array([[1,2,3] , [4,5,6]])

In [10]:
np.concatenate( [a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [11]:
np.concatenate( [a,a] , axis = 1 )
#satir bazinda birlestirme icin 0 , sutun 1 default 0

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])