In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3,4,5])

In [3]:
v -1

array([0, 1, 2, 3, 4])

In [4]:
#denkligi:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [5]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [6]:
np.multiply(v,5)

array([ 5, 10, 15, 20, 25])

In [8]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [9]:
np.absolute(np.array([-3]))

array([3])

In [10]:
np.cos(180)

-0.5984600690578581

In [11]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])