In [1]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
#sifirdan array olusturma
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((3,5) , 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [7]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [8]:
np.linspace(0,1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
np.random.normal(10,4, (3,4))

array([[ 8.91370667, 20.04530375, 12.51182786,  5.18457717],
       [10.34344133, 15.98203833,  7.98911205,  8.29689178],
       [16.31868169, 14.52894942, 10.72645829, 15.87899193]])

In [10]:
np.random.randint(0,10, (3,3))

array([[3, 6, 1],
       [4, 0, 7],
       [4, 5, 2]])