In [1]:
import numpy as np

In [ ]:
# 5* xo +x1= 12
# xo+ 3*x1= 10

In [4]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [7]:
a


array([[5, 1],
       [1, 3]])

In [6]:
b

array([12, 10])

In [8]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])