In [1]:
import numpy as np

In [3]:
a = np.arange(1,10)

In [4]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a = np.arange(1,10).reshape((3,3))

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
b = np.arange(1,10)

In [8]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b.ndim

1

In [13]:
c = b.reshape((1,9))
#dikkatli bak koseli parantez bu ciktida 2

In [14]:
c.ndim

2